version: '3.8'

services:
  db:
    image: postgres
    container_name: supermercado_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: supermercado_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: .
    container_name: supermercado_server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
